### ISSUE TITLE
The `set-output` command is deprecated

### ISSUE THREAD

**Issue by andrewc12** [suisei-cn/actions-download-file#12]
When I use this action like this I get the following warning

```yaml
    - name: Download Inno Setup istaller
      uses: suisei-cn/actions-download-file@v1.0.1
      id: innoinstaller
      with:
        url: 'https://jrsoftware.org/download.php/is.exe'
        target: ${{github.workspace}}/
```

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The warning itself can be seen here.
https://github.com/andrewc12/openzfs/actions/runs/3418851796
