### ISSUE TITLE
Please print the output name of the saved file

### ISSUE THREAD

**Issue by pdange** [suisei-cn/actions-download-file#5]
It is very confusing to understand what the name of file saved is.
Can you please add a console.log for filename, so we can export it in Git hub action using upload-artifacts.

https://github.com/suisei-cn/actions-download-file/blob/0602fa521a4810cf565a77c8bb896382a163450a/dist/index.js#L455-L458

Thanks.

**Comment by outloudvi** [comment]
Hi, we provide [the output parameter `filename`](https://github.com/suisei-cn/actions-download-file#output) for this purpose (as seen by the line 456 in your quoted code).

If you want to have the filename used for later steps, give this action an `id` and use that later. For example:

``` yml
- uses: suisei-cn/actions-download-file@v1
  id: downloadfile
  with:
    url: "https://example.com"
    # other fields omitted

- name: Display the name of the downloaded file
  run: echo "The file is named ${{ steps.downloadfile.outputs.filename }}"
```

If you want to see a more complete example, check the [`auto_pr.yml`](https://github.com/suisei-cn/sbtn-assets/blob/d4eb42ab1f4458f62ff783c48d87e8a304f355e2/.github/workflows/auto_pr.yml#L37) in suisei-cn/sbtn-assets.

**Comment by pdange** [comment]
So, Is this valid format?

```
- uses: suisei-cn/actions-download-file@v1
   id: downloadfile
   with:
    url: "https://example.com"
    target: /path/to/folder/
    filename: XYZ.txt
```
Regards,
PD

**Comment by outloudvi** [comment]
I think you caught my point, but just one problem: indentation. `uses`, `id` and `with` should be at the same level:

``` yml
-  uses: suisei-cn/actions-download-file@v1
   id: downloadfile
   with:
    url: "https://example.com"
    target: /path/to/folder/
    filename: XYZ.txt
```
