### ISSUE TITLE
Error after downloading

### ISSUE THREAD

**Issue by noonchen** [suisei-cn/actions-download-file#6]
Here is the script:
```
- uses: suisei-cn/actions-download-file@v1
  id: numpy_vanilla
  name: Download numpy vanilla
  with:
    url: "https://www.lfd.uci.edu/~gohlke/pythonlibs/#:~:text=numpy%E2%80%911.21.4%2Bvanilla%E2%80%91cp39%E2%80%91cp39%E2%80%91win_amd64.whl"
    target: "mydownloads"
```

Runtime log:
```
Run suisei-cn/actions-download-file@v1
  with:
    url: https://www.lfd.uci.edu/~gohlke/pythonlibs/#:~:text=numpy%E2%80%911.21.4%2Bvanilla%E2%80%91cp39%E2%80%91cp39%E2%80%91win_amd64.whl
    target: mydownloads
    auto-match: false
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.9.8\x64
URL found: https://www.lfd.uci.edu/~gohlke/pythonlibs/#:~:text=numpy%E2%80%911.21.4%2Bvanilla%E2%80%91cp39%E2%80%91cp39%E2%80%91win_amd64.whl
Download completed.
Error: EISDIR: illegal operation on a directory, open 'mydownloads'
```
Am I using the syntax in the wrong way?
