### ISSUE TITLE
Download Image

### ISSUE THREAD

**Issue by Angelk90** [suisei-cn/actions-download-file#8]
Hi @outloudvi , would it be possible to download an image and save it in the repository?

I tried to do a similar thing but it doesn't seem to work:

```
on: 
  workflow_dispatch:
name: Scrape File
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit
          
      - uses: suisei-cn/actions-download-file@v1
        id: downloadfile
        name: Download the file
        with:
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Meet_Truffle%21.jpg/440px-Meet_Truffle%21.jpg"
          target: assets/
```

How can I do?
